run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      Main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/Kiba70/otus/internal/config
          - github.com/Kiba70/otus/internal/cpu
          - github.com/Kiba70/otus/internal/loadavg
          - github.com/Kiba70/otus/internal/netstat
          - github.com/Kiba70/otus/internal/process
          - github.com/Kiba70/otus/internal/web
          - github.com/Kiba70/otus/internal/pb
          - github.com/Kiba70/otus/internal/myerr
          - github.com/Kiba70/otus/internal/storage
          - google.golang.org/grpc
          - google.golang.org/grpc/credentials/insecure
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/stretchr/testify
          - github.com/Kiba70/otus/internal/config
          - github.com/Kiba70/otus/internal/cpu
          - github.com/Kiba70/otus/internal/loadavg
          - github.com/Kiba70/otus/internal/netstat
          - github.com/Kiba70/otus/internal/process
          - github.com/Kiba70/otus/internal/web
          - github.com/Kiba70/otus/internal/pb
          - github.com/Kiba70/otus/internal/myerr
          - github.com/Kiba70/otus/internal/storage
          - google.golang.org/grpc
          - google.golang.org/grpc/credentials/insecure

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
