// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: api/monitoring.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        int32                  `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
	Seconds       int32                  `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_api_monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *Request) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

type LoadAvgReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	One           float32                `protobuf:"fixed32,1,opt,name=one,proto3" json:"one,omitempty"`
	Five          float32                `protobuf:"fixed32,2,opt,name=five,proto3" json:"five,omitempty"`
	Fifteen       float32                `protobuf:"fixed32,3,opt,name=fifteen,proto3" json:"fifteen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadAvgReply) Reset() {
	*x = LoadAvgReply{}
	mi := &file_api_monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadAvgReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAvgReply) ProtoMessage() {}

func (x *LoadAvgReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAvgReply.ProtoReflect.Descriptor instead.
func (*LoadAvgReply) Descriptor() ([]byte, []int) {
	return file_api_monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *LoadAvgReply) GetOne() float32 {
	if x != nil {
		return x.One
	}
	return 0
}

func (x *LoadAvgReply) GetFive() float32 {
	if x != nil {
		return x.Five
	}
	return 0
}

func (x *LoadAvgReply) GetFifteen() float32 {
	if x != nil {
		return x.Fifteen
	}
	return 0
}

type CpuReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          float32                `protobuf:"fixed32,1,opt,name=user,proto3" json:"user,omitempty"`
	System        float32                `protobuf:"fixed32,2,opt,name=system,proto3" json:"system,omitempty"`
	Idle          float32                `protobuf:"fixed32,3,opt,name=idle,proto3" json:"idle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuReply) Reset() {
	*x = CpuReply{}
	mi := &file_api_monitoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuReply) ProtoMessage() {}

func (x *CpuReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuReply.ProtoReflect.Descriptor instead.
func (*CpuReply) Descriptor() ([]byte, []int) {
	return file_api_monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *CpuReply) GetUser() float32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *CpuReply) GetSystem() float32 {
	if x != nil {
		return x.System
	}
	return 0
}

func (x *CpuReply) GetIdle() float32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

type NetstatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Socket        []*NetstatSocketReply  `protobuf:"bytes,1,rep,name=socket,proto3" json:"socket,omitempty"`
	Conn          map[string]int32       `protobuf:"bytes,2,rep,name=conn,proto3" json:"conn,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetstatReply) Reset() {
	*x = NetstatReply{}
	mi := &file_api_monitoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetstatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetstatReply) ProtoMessage() {}

func (x *NetstatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetstatReply.ProtoReflect.Descriptor instead.
func (*NetstatReply) Descriptor() ([]byte, []int) {
	return file_api_monitoring_proto_rawDescGZIP(), []int{3}
}

func (x *NetstatReply) GetSocket() []*NetstatSocketReply {
	if x != nil {
		return x.Socket
	}
	return nil
}

func (x *NetstatReply) GetConn() map[string]int32 {
	if x != nil {
		return x.Conn
	}
	return nil
}

type NetstatSocketReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetstatSocketReply) Reset() {
	*x = NetstatSocketReply{}
	mi := &file_api_monitoring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetstatSocketReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetstatSocketReply) ProtoMessage() {}

func (x *NetstatSocketReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_monitoring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetstatSocketReply.ProtoReflect.Descriptor instead.
func (*NetstatSocketReply) Descriptor() ([]byte, []int) {
	return file_api_monitoring_proto_rawDescGZIP(), []int{4}
}

func (x *NetstatSocketReply) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *NetstatSocketReply) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *NetstatSocketReply) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *NetstatSocketReply) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetstatSocketReply) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_api_monitoring_proto protoreflect.FileDescriptor

var file_api_monitoring_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3b, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x4e, 0x0a, 0x0c, 0x4c, 0x6f, 0x61, 0x64, 0x41,
	0x76, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x76,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x66, 0x69, 0x76, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x66, 0x69, 0x66, 0x74, 0x65, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07,
	0x66, 0x69, 0x66, 0x74, 0x65, 0x65, 0x6e, 0x22, 0x4a, 0x0a, 0x08, 0x43, 0x70, 0x75, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x69,
	0x64, 0x6c, 0x65, 0x22, 0xa7, 0x01, 0x0a, 0x0c, 0x4e, 0x65, 0x74, 0x73, 0x74, 0x61, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x73, 0x74, 0x61,
	0x74, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x06, 0x73, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x73, 0x74, 0x61, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04,
	0x63, 0x6f, 0x6e, 0x6e, 0x1a, 0x37, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x6e, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x84, 0x01,
	0x0a, 0x12, 0x4e, 0x65, 0x74, 0x73, 0x74, 0x61, 0x74, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x32, 0xa0, 0x01, 0x0a, 0x0a, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x32, 0x0a, 0x0d, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x67, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x6e, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x67, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2a, 0x0a, 0x09, 0x43, 0x70, 0x75, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x6e, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x70, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x32, 0x0a, 0x0d, 0x4e, 0x65, 0x74, 0x73, 0x74, 0x61, 0x74, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x6e, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x73, 0x74, 0x61, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_monitoring_proto_rawDescOnce sync.Once
	file_api_monitoring_proto_rawDescData = file_api_monitoring_proto_rawDesc
)

func file_api_monitoring_proto_rawDescGZIP() []byte {
	file_api_monitoring_proto_rawDescOnce.Do(func() {
		file_api_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_monitoring_proto_rawDescData)
	})
	return file_api_monitoring_proto_rawDescData
}

var file_api_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_monitoring_proto_goTypes = []any{
	(*Request)(nil),            // 0: pb.Request
	(*LoadAvgReply)(nil),       // 1: pb.LoadAvgReply
	(*CpuReply)(nil),           // 2: pb.CpuReply
	(*NetstatReply)(nil),       // 3: pb.NetstatReply
	(*NetstatSocketReply)(nil), // 4: pb.NetstatSocketReply
	nil,                        // 5: pb.NetstatReply.ConnEntry
}
var file_api_monitoring_proto_depIdxs = []int32{
	4, // 0: pb.NetstatReply.socket:type_name -> pb.NetstatSocketReply
	5, // 1: pb.NetstatReply.conn:type_name -> pb.NetstatReply.ConnEntry
	0, // 2: pb.Monitoring.LoadAvgGetMon:input_type -> pb.Request
	0, // 3: pb.Monitoring.CpuGetMon:input_type -> pb.Request
	0, // 4: pb.Monitoring.NetstatGetMon:input_type -> pb.Request
	1, // 5: pb.Monitoring.LoadAvgGetMon:output_type -> pb.LoadAvgReply
	2, // 6: pb.Monitoring.CpuGetMon:output_type -> pb.CpuReply
	3, // 7: pb.Monitoring.NetstatGetMon:output_type -> pb.NetstatReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_monitoring_proto_init() }
func file_api_monitoring_proto_init() {
	if File_api_monitoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_monitoring_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_monitoring_proto_goTypes,
		DependencyIndexes: file_api_monitoring_proto_depIdxs,
		MessageInfos:      file_api_monitoring_proto_msgTypes,
	}.Build()
	File_api_monitoring_proto = out.File
	file_api_monitoring_proto_rawDesc = nil
	file_api_monitoring_proto_goTypes = nil
	file_api_monitoring_proto_depIdxs = nil
}
