name: Otus final project

on:
  push:
    branches:
      - dev

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'calendar') }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.24

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.8
          working-directory: /home/runner/work/otus/otus

  tests:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'calendar') }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.24

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: go test -tags=linux -count=100 -race -timeout=1m ./internal/...
        working-directory: /home/runner/work/otus/otus

      - name: Integration test
        run: make integration
        working-directory: /home/runner/work/otus/otus