name: Otus final project

on:
  push:
    branches:
      - dev
      - main

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'calendar') }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.24

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v2.0.2
          working-directory: /home/runner/work/otus/otus

  tests:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'calendar') }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.24

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: go test -tags=linux -count=100 -race -timeout=1m ./internal/...
        working-directory: /home/runner/work/otus/otus

      - name: Integration test
        run: make integration
        working-directory: /home/runner/work/otus/otus

  build-linux:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'calendar') }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.24

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build server
        run: go build tags=linux -o ./bin/server ./cmd/server
        working-directory: /home/runner/work/otus/otus

      - name: Build client
        run: go build tags=linux -o ./bin/client ./cmd/client
        working-directory: /home/runner/work/otus/otus

  build-windows:
    runs-on: windows-latest
    if: ${{ !contains(github.ref, 'calendar') }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.24

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build server
        run: go build tags=windows -o ./bin/server.exe ./cmd/server
        working-directory: /home/runner/work/otus/otus

      - name: Build client
        run: go build tags=windows -o ./bin/client.exe ./cmd/client
        working-directory: /home/runner/work/otus/otus